/**
 * Contract tests for configuration storage functions
 * Tests the storeConfiguration and checkDuplicateReportName functions
 */

const { describe, it, expect, beforeEach, afterEach } = require('@jest/globals');

// Mock the Google Apps Script environment
require('../unit/mocks');

// Import the functions to test
const { storeConfiguration, checkDuplicateReportName } = require('../../script/ai-report-generator');

describe('Configuration Storage Contract Tests', () => {
  let mockSpreadsheet;
  let mockSheet;
  let mockRange;

  beforeEach(() => {
    // Setup fresh mocks for each test
    mockRange = {
      setValues: jest.fn(),
      getValues: jest.fn().mockReturnValue([]),
      setFontWeight: jest.fn()
    };

    mockSheet = {
      getRange: jest.fn().mockReturnValue(mockRange),
      getLastRow: jest.fn().mockReturnValue(1), // Only headers initially
      getName: jest.fn().mockReturnValue('Report Configs')
    };

    mockSpreadsheet = {
      getSheetByName: jest.fn(),
      insertSheet: jest.fn().mockReturnValue(mockSheet)
    };

    // Mock SpreadsheetApp.getActiveSpreadsheet()
    global.SpreadsheetApp.getActiveSpreadsheet.mockReturnValue(mockSpreadsheet);
  });

  afterEach(() => {
    jest.clearAllMocks();
  });

  describe('storeConfiguration() Function', () => {
    
    it('should create new Report Configs sheet if it does not exist', () => {
      // Arrange: Make getSheetByName throw error (sheet doesn't exist)
      mockSpreadsheet.getSheetByName.mockImplementation(() => {
        throw new Error('Sheet not found');
      });

      const testConfig = {
        reportName: 'Test Report',
        description: 'Test Description',
        columns: 'Date,Hours',
        summaryType: 'SUM',
        outputStructure: 'SINGLE_SHEET'
      };

      // Act
      const result = storeConfiguration(testConfig);

      // Assert
      expect(mockSpreadsheet.insertSheet).toHaveBeenCalledWith('Report Configs');
      expect(mockSheet.getRange).toHaveBeenCalledWith(1, 1, 1, 8); // Headers
      expect(mockRange.setValues).toHaveBeenCalledWith([[
        'Name', 'Description', 'Columns', 'Filters', 'Sort By', 'Sort Order', 'Summary Type', 'Output Structure'
      ]]);
      expect(mockRange.setFontWeight).toHaveBeenCalledWith('bold');
      expect(result.success).toBe(true);
      expect(result.sheetName).toBe('Report Configs');
    });

    it('should store configuration in existing Report Configs sheet', () => {
      // Arrange: Mock existing sheet
      mockSpreadsheet.getSheetByName.mockReturnValue(mockSheet);
      mockSheet.getLastRow.mockReturnValue(2); // Has 1 data row already

      const testConfig = {
        reportName: 'Monthly Report',
        description: 'Monthly hours summary',
        columns: 'Member,Project,Hours',
        filters: 'Active=true',
        sortBy: 'Hours',
        sortOrder: 'DESC',
        summaryType: 'SUM',
        outputStructure: 'SHEET_PER_PROJECT'
      };

      // Act
      const result = storeConfiguration(testConfig);

      // Assert
      expect(mockSpreadsheet.getSheetByName).toHaveBeenCalledWith('Report Configs');
      expect(mockSheet.getLastRow).toHaveBeenCalled();
      expect(mockSheet.getRange).toHaveBeenCalledWith(3, 1, 1, 8); // Row 3 (next empty)
      expect(mockRange.setValues).toHaveBeenCalledWith([[
        'Monthly Report',
        'Monthly hours summary',
        'Member,Project,Hours',
        'Active=true',
        'Hours',
        'DESC',
        'SUM',
        'SHEET_PER_PROJECT'
      ]]);
      expect(result.success).toBe(true);
      expect(result.row).toBe(3);
      expect(result.configName).toBe('Monthly Report');
    });

    it('should handle minimal configuration with defaults', () => {
      // Arrange
      mockSpreadsheet.getSheetByName.mockReturnValue(mockSheet);

      const minimalConfig = {
        reportName: 'Simple Report'
      };

      // Act
      const result = storeConfiguration(minimalConfig);

      // Assert
      expect(mockRange.setValues).toHaveBeenCalledWith([[
        'Simple Report',
        'Generated by AI',
        '',
        '',
        '',
        '',
        'NONE',
        'SINGLE_SHEET'
      ]]);
      expect(result.success).toBe(true);
    });

    it('should handle storage errors gracefully', () => {
      // Arrange: Mock SpreadsheetApp to throw error
      global.SpreadsheetApp.getActiveSpreadsheet.mockImplementation(() => {
        throw new Error('No active spreadsheet');
      });

      const testConfig = { reportName: 'Test' };

      // Act
      const result = storeConfiguration(testConfig);

      // Assert
      expect(result.success).toBe(false);
      expect(result.error).toContain('Failed to store configuration');
    });

  });

  describe('checkDuplicateReportName() Function', () => {
    
    it('should return no duplicate when Report Configs sheet does not exist', () => {
      // Arrange
      mockSpreadsheet.getSheetByName.mockImplementation(() => {
        throw new Error('Sheet not found');
      });

      // Act
      const result = checkDuplicateReportName('New Report');

      // Assert
      expect(result.success).toBe(true);
      expect(result.isDuplicate).toBe(false);
    });

    it('should return no duplicate when sheet is empty', () => {
      // Arrange
      mockSpreadsheet.getSheetByName.mockReturnValue(mockSheet);
      mockSheet.getLastRow.mockReturnValue(1); // Only headers

      // Act
      const result = checkDuplicateReportName('New Report');

      // Assert
      expect(result.success).toBe(true);
      expect(result.isDuplicate).toBe(false);
    });

    it('should detect exact name duplicate (case-insensitive)', () => {
      // Arrange
      mockSpreadsheet.getSheetByName.mockReturnValue(mockSheet);
      mockSheet.getLastRow.mockReturnValue(3); // 2 data rows
      mockRange.getValues.mockReturnValue([
        ['Existing Report'],
        ['Another Report']
      ]);

      // Act
      const result = checkDuplicateReportName('EXISTING REPORT');

      // Assert
      expect(result.success).toBe(true);
      expect(result.isDuplicate).toBe(true);
      expect(result.suggestedName).toBe('EXISTING REPORT (Copy)');
    });

    it('should return no duplicate for unique name', () => {
      // Arrange
      mockSpreadsheet.getSheetByName.mockReturnValue(mockSheet);
      mockSheet.getLastRow.mockReturnValue(3);
      mockRange.getValues.mockReturnValue([
        ['Existing Report'],
        ['Another Report']
      ]);

      // Act
      const result = checkDuplicateReportName('Unique Report');

      // Assert
      expect(result.success).toBe(true);
      expect(result.isDuplicate).toBe(false);
      expect(result.suggestedName).toBe('Unique Report');
    });

    it('should handle empty cells in name column', () => {
      // Arrange
      mockSpreadsheet.getSheetByName.mockReturnValue(mockSheet);
      mockSheet.getLastRow.mockReturnValue(4);
      mockRange.getValues.mockReturnValue([
        ['Valid Report'],
        [''],
        [null]
      ]);

      // Act
      const result = checkDuplicateReportName('New Report');

      // Assert
      expect(result.success).toBe(true);
      expect(result.isDuplicate).toBe(false);
    });

    it('should handle duplicate check errors gracefully', () => {
      // Arrange
      global.SpreadsheetApp.getActiveSpreadsheet.mockImplementation(() => {
        throw new Error('Access denied');
      });

      // Act
      const result = checkDuplicateReportName('Test Report');

      // Assert
      expect(result.success).toBe(false);
      expect(result.error).toContain('Failed to check duplicates');
    });

  });

});
